# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'WeatherApp' do

  # Pods for WeatherApp

	pod 'SwiftLint'

  target 'WeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherAppUITests' do
    # Pods for testing
  end

end
